### ISSUE TITLE
Weed resupply

### ISSUE THREAD

**Issue by PSHacks** [YimMenu-Lua/YimResupplier#1]
Hi! The trouble is, cocaine works well, but weed resupply got NULL text message on phone, seems like "(1662873 + 1 + 3, 1)" wrong or something.. 

![21 37 35_04 02 2024](https://github.com/YimMenu-Lua/YimResupplier/assets/5302606/318f7f3a-60d5-4e70-8f9b-87ded7e6c203)

**Comment by xesdoog** [comment]
Is this happening with weed only?

**Comment by xesdoog** [comment]
Do you have an ACTIVE weed business?
