### ISSUE TITLE
[REQUEST] upgrades checkbox status 

### ISSUE THREAD

**Issue by alanwang96** [YimMenu-Lua/YimResupplier#12]
![Grand Theft Auto V 2024_12_20 11_13_10](https://github.com/user-attachments/assets/5eb19c1c-abff-49e0-8da9-a0da2d4d4d87)
my bunker and mc factories are confirmed fully upgraded, but in menu every checkbox is unmarked as shown.it misleads me that i thought i lost all ungrades using ur lua at first sight.
it should read my stats ,preload checkbox status marked/unmarked , prohibit degrades ( since in vanilla game there is no way u can legit do it ,except buy another factory without any updates, and its unnecessary ) ,avoid  duplicated upgrades. i would be appreciated if these freatures can be realized .

**Comment by xesdoog** [comment]
> ![Grand Theft Auto V 2024_12_20 11_13_10](https://private-user-images.githubusercontent.com/54777557/397602558-5eb19c1c-abff-49e0-8da9-a0da2d4d4d87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2NjgwMDIsIm5iZiI6MTczNDY2NzcwMiwicGF0aCI6Ii81NDc3NzU1Ny8zOTc2MDI1NTgtNWViMTljMWMtYWJmZi00OWUwLThkYTktYTBkYTJkNGQ0ZDg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDA0MDgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjNWFkNDY3MWIzZTk5Y2RjYTlmYzdiZDIzYTEyNTcyYTNjNzExMDBmMzBhMGNlNzQ0YTQxZWM3NjQ4MTc5MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.35h_Pn5fpP7lLlum-PFf9C6onibkBjq_IPiueMTU0OY) my bunker and mc factories are confirmed fully upgraded, but in menu every checkbox is unmarked as shown.it misleads me that i thought i lost all ungrades using ur lua at first sight. it should read my stats ,preload checkbox status marked/unmarked , prohibit degrades ( since in vanilla game there is no way u can legit do it ,except buy another factory without any updates, and its unnecessary ) ,avoid duplicated upgrades. i would be appreciated if these freatures can be realized .

Those don't read any globals or stats and they don't enable or disable upgrades. They're only there to show you how much your stock would be worth with and without upgrades. You just have to manually check them to adjust the displayed prices.
