### ISSUE TITLE
After update of RS, script need to update.

### ISSUE THREAD

**Issue by heni015** [YimMenu-Lua/YimResupplier#3]
Script all the time showing:
![image](https://github.com/YimMenu-Lua/YimResupplier/assets/49375523/30254e36-9703-42f6-8640-bbe1f4c9f845)
I don't know that we need change a variables or just change in script from 3095 to 3179, but I wanna notify about it.

**Comment by xesdoog** [comment]
That is a security measure in case globals change. In this case it was just a build version change and I completely forgot about it. Fixed version is up.
