### ISSUE TITLE
[Request] Warehouse Staff Sourcing

### ISSUE THREAD

**Issue by ewenjam** [YimMenu-Lua/YimResupplier#4]
Would you consider adding the option to have the CEO Warehouses get resupplied through the Staff Sourcing feature?

I don't mean instantly filling the warehouse, just the option to trigger them to go source for crates (it takes them 45 mins to source once started IIRC, per warehouse). 

Its more of a QoL addition to avoid having to go to each warehouse and talking to the staff, since R* decided that you can't just call them from your phone.

![Capture - Copy](https://github.com/YimMenu-Lua/YimResupplier/assets/159111807/19024001-42bb-4059-ac21-ffaa8f038d93)

Regardless, thank you for this great script. Its incredibly useful 😄

**Comment by xesdoog** [comment]
Sure, I'll add it when I get off work.
Please keep in mind that I will not be able to properly check how many warehouses a player owns because that would need some time which I don't currently have but I will simply assume that you own all 5 warehouses and act accordingly.
