### ISSUE TITLE
Not up to date

### ISSUE THREAD

**Issue by THE-SIMPLE-MARK** [YimMenu-Lua/YimResupplier#6]
Upon clicking the menu option, it greets me with "YimResupplier is not up to date":
![image](https://github.com/user-attachments/assets/4175a3f9-eb3b-49b7-9296-e08a5dd0aecd)

**Comment by xesdoog** [comment]
Hey @THE-SIMPLE-MARK , 

I'm not home right now and I'm kinda shitfaced but if you're available to test, I can just bump the version and wait for you to try it and tell me if every option works or not. Everything should work since afaik nothing was changed with the new update apart form stuff related to BE.

**Comment by gabriel-mont** [comment]
I mean, that SHOULD work, if you want to try it, maybe I can test it as of rn I'm having the same problem

**Comment by xesdoog** [comment]
> I mean, that SHOULD work, if you want to try it, maybe I can test it as of rn I'm having the same problem

Alright, I'll set up a test branch then send you a link

**Comment by THE-SIMPLE-MARK** [comment]
> > I mean, that SHOULD work, if you want to try it, maybe I can test it as of rn I'm having the same problem
> 
> Alright, I'll set up a test branch then send you a link

Alright, sure.

I should also probably mention that I moved to “Samurais-Scripts” because the one in there worked and said that it has more features.

**Comment by xesdoog** [comment]
here's the test branch: https://github.com/YimMenu-Lua/YimResupplier/tree/test

> the one in there worked and said that it has more features.

If that works then this will work too since they are basically the same.

**Comment by THE-SIMPLE-MARK** [comment]
> here's the test branch: https://github.com/YimMenu-Lua/YimResupplier/tree/test
> 
> > the one in there worked and said that it has more features.
> 
> If that works then this will work too since they are basically the same.

Awesome! I’m gonna test it in a couple of hours. Will let you know.

**Comment by gabriel-mont** [comment]
It's working flawlessly now, sorry for making you wait, went asleep for a bit, thanks dude!

**Comment by THE-SIMPLE-MARK** [comment]
> It's working flawlessly now, sorry for making you wait, went asleep for a bit, thanks dude!

No worries! And I should be the one thanking you. Thanks for maintaining these extensions :)

**Comment by xesdoog** [comment]
Thank you both for the help, I appreciate it.
I'll merge the changes from the test branch into main.

**Comment by THE-SIMPLE-MARK** [comment]
Omg I just realized that there were 2 different people in this conversation 😅

My replies are so confusing in hindsight
