### ISSUE TITLE
YimResupplier Bug

### ISSUE THREAD

**Issue by jayelp97** [YimMenu-Lua/YimResupplier#8]
Unable to see the whole menu on the production overview. Was there something I did wrong or is that an internal issue? 
![image](https://github.com/user-attachments/assets/04744a3a-880e-48f6-bcc1-ff7d299a2a9c)

**Comment by xesdoog** [comment]
Paste your log here please. (%AppData%\YimMenu\cout.log)

**Comment by jayelp97** [comment]
[cout.log](https://github.com/user-attachments/files/17105209/cout.log)

**Comment by jayelp97** [comment]
I have also done a fresh install of the YimResupplier and also YimMenu itself

**Comment by xesdoog** [comment]
Do you own a CEO warehouse?

**Comment by jayelp97** [comment]
Yup, I own all businesses

**Comment by jayelp97** [comment]
Well sorry for wasting your time, it just fixed itself as I tried opening it again. I didnt do anything different so idk what happened. Thanks anyways lol Sorry :)
